### ISSUE TITLE
Server 500 Error - One-Step Retrosynthesis, ASKCOS v0.2.9

### ISSUE THREAD

**Issue by Amar1729** [connorcoley/ASKCOS#45]
We are currently using an outdated version of ASKCOS on an internal network on RHEL7. We've installed relevant dependencies and pip modules manually and have the server working and displaying a home page and many of the top-level links work. Due to our network restrictions, we are NOT running this in Docker but instead have a run script roughly based on this repo's docker-compose.yml, which runs uwsgi and each worker in the background when started.

However, when navigating to One-Step Retrosynthesis and clicking on any molecules, we get a Server 500 error with no relevant log messages. I've done some digging and found that the following stacktrace -

From `askcos_site.main.views.retro:149`, when `res.get` is called,
  - https://github.com/ASKCOS/ASKCOS/blob/v0.2.9/askcos/askcos_site/main/views/retro.py#L149

We see the following error:
```
[2021-07-28 17:46:57,314: ERROR/ForkPoolWorker-8] Task askcos_site.askcos_celery.treebuilder.tb_c_worker.get_top_precursors[ea24cc1b-0bde-46c4-895b-5127c92dc0c2] raised unexpected: AttributeError("'NoneType' object has no attribute 'get_outcomes'",)
Traceback (most recent call last):
  File "/home/paula1/ASKCOS/env/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/paula1/ASKCOS/env/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/paula1/ASKCOS/askcos/askcos_site/askcos_celery/treebuilder/tb_c_worker.py", line 60, in get_top_precursors
    result = retroTransformer.get_outcomes(
AttributeError: 'NoneType' object has no attribute 'get_outcomes'
```

- https://github.com/ASKCOS/ASKCOS/blob/v0.2.9/askcos/askcos_site/askcos_celery/treebuilder/tb_c_worker.py#L60

It seems that the `global retroTransformer` is still `NoneType` when its `.get_outcomes` method is called.

Have you seen a similar error, or have an idea for possible workarounds with v0.2.9? We're operating this on a VM with the minimum required mem/cpu cores for ASKCOS v0.2.9, but upgrading to current v0.4.1 is somewhat difficult due to our requirement to use a RHEL VM rather than Docker (and since your docker images are ubuntu-based, porting the docker builds is not trivial).

**Comment by mliu49** [comment]
Hi @Amar1729, I don't have any experience with v0.2.9, so this is just a hypothesis based on newer versions of ASKCOS. The fact that retroTransformer is still None means that the instantiation ([here](https://github.com/ASKCOS/ASKCOS/blob/v0.2.9/askcos/askcos_site/askcos_celery/treebuilder/tb_c_worker.py#L36)) failed for some reason, and the most common reason in my experience is an issue with importing tensorflow. This is often related to the fact that tensorflow is not fork-safe, so import order and when tensorflow is imported can matter. Unfortunately I don't have any ideas for specific workarounds which would fix the issue.
